[project]
name = "tart-linux-images"
version = "0.1.0"
authors = [
    { name = "pythoninthegrass", email = "4097471+pythoninthegrass@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.6.0",
    "ansible-lint>=25.4.0",
]
